Updated

diff --git a/scripts/countdown b/scripts/countdown
--- a/scripts/countdown
+++ b/scripts/countdown
@@ -1,12 +1,16 @@
 #!/bin/env bash
-start="$(( $(date +%s) + $1))"
+if [ -z "$1" ] || ! [[ "$1" =~ ^[0-9]+$ ]] || [ "$1" -le 0 ]; then
+  echo "Invalid input"
+  exit 1
+fi
+start="$(($(date +%s) + $1))"
 while [ "$start" -ge $(date +%s) ]; do
-    ## Is this more than 24h away?
-    # days="$(($(($(( $start - $(date +%s) )) * 1 )) / 86400))"
-    time="$(( $start - `date +%s` ))"
-    # printf '%s day(s) and %s\r' "$days" "$(date -u -d "@$time" +%H:%M:%S)"
-    printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
-    sleep 0.5
+  ## Is this more than 24h away?
+  # days="$(($(($(( $start - $(date +%s) )) * 1 )) / 86400))"
+  time="$(($start - $(date +%s)))"
+  # printf '%s day(s) and %s\r' "$days" "$(date -u -d "@$time" +%H:%M:%S)"
+  printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
+  sleep 0.5
 done
 notify-send "Time's up"
 /usr/bin/paplay /usr/share/sounds/freedesktop/stereo/complete.oga
