Updated

diff --git a/scripts/LBsync b/scripts/LBsync
--- a/scripts/LBsync
+++ b/scripts/LBsync
@@ -5,6 +5,7 @@ data_dir="/media/data/Linux_Backup/dotfiles/"
 
 GREEN='\e[32m'
 RED='\e[31m'
+YELLOW='\e[33m'
 RESET='\e[0m'
 
 cd "${dotfiles_dir}" || {
@@ -14,7 +15,7 @@ cd "${dotfiles_dir}" || {
 git pull origin main --rebase || exit
 git rm -rf .
 
-file_list=(
+dotfiles=(
   "/etc/keyd/default.conf"
   "/etc/tlp.conf"
   "/etc/auto-cpufreq.conf"
@@ -48,14 +49,14 @@ file_list=(
 )
 
 function push() {
-  echo -e "${GREEN}Uploading $1 to Github${RESET}"
+  echo -e "${GREEN}Uploading $1 to Github$RESET"
   git add .
   if git diff --staged --quiet; then
     echo "No changes to commit."
     return 0
   fi
   git commit -m "Updated" || {
-    echo "${RED}Git commit failed!${RESET}"
+    echo "${RED}Git commit failed!$RESET"
     exit 1
   }
   git push -u origin main
@@ -63,7 +64,7 @@ function push() {
 
 function copyDots() {
   mkdir -p "$1"
-  for item in "${file_list[@]}"; do
+  for item in "${dotfiles[@]}"; do
     if [ -e "$item" ]; then
       relative_path="${item#~/}"
       if [[ $item == /etc/* ]]; then
@@ -71,17 +72,16 @@ function copyDots() {
       fi
       destination_dir=$(dirname "$1$relative_path")
       mkdir -p "$destination_dir"
-      cp -r "$item" "$destination_dir"
-      if [ $? -ne 0 ]; then
-        echo -e "${RED}ERROR: cannot copy $item.${RESET}"
+      if ! cp -r "$item" "$destination_dir"; then
+        echo -e "${RED}ERROR: couldn't copy $item.$RESET"
       else
         echo -e "Copied: $item to $destination_dir"
       fi
     else
-      echo -e "${RED}ERROR: $item does not exist.${RESET}"
+      echo -e "${RED}ERROR: $item does not exist.$RESET"
     fi
   done
-  echo -e "${GREEN}Copying completed.\n${RESET}"
+  echo -e "${GREEN}Copying to $1 completed.\n$RESET"
 }
 
 copyDots "$dotfiles_dir"
@@ -93,7 +93,7 @@ if [ -w "$data_dir" ]; then
   rm -rf "$data_dir" || exit
   copyDots "$data_dir"
 else
-  echo -e "Skipping $data_dir"
+  echo -e "${YELLOW}Skipping $data_dir $RESET"
   exit 1
 fi
 
diff --git a/scripts/picker b/scripts/picker
--- a/scripts/picker
+++ b/scripts/picker
@@ -5,6 +5,7 @@
 # Supports emoji, nerdfont, unicode, ansi styles/controls/keycodes
 # Can be opened normally or floating mode
 # Floating mode exits automatically after copying, normal mode can be exited with Ctrl-C
+# you can use --prefix <ansi_code> to apply an ANSI code to items preview in ansi_styles picker
 
 # --- Configuration ---
 TERMINAL="foot"
@@ -58,6 +59,18 @@ elif [[ "$2" == "$FLOAT_ARG" ]]; then
   PICKER_TYPE="$1"
 else
   PICKER_TYPE="$1"
+fi
+
+PREFIX_ARG="--prefix"
+# prefix arg handling
+if [[ "$2" == "$PREFIX_ARG" ]]; then
+  # Get the value which is the next argument
+  if [[ -n "$3" ]]; then
+    PREFIX_CODE="$3"
+  else
+    echo "Error: --prefix requires an ANSI code argument" >&2
+    exit 1
+  fi
 fi
 
 # --- Picker for pickers ---
@@ -168,8 +181,11 @@ INNER_EOF
 
   export FZF_DEFAULT_OPTS="$FZF_OPTS_BASE $fzf_extra_opts"
 
-  eval "$data_cmd" | fzf --bind="enter:execute-silent($copy_notify_cmd)"
+  if [[ -n "$PREFIX_CODE" ]]; then
+    eval "$data_cmd" | fzf --bind="enter:execute-silent($copy_notify_cmd)" --preview="echo -e \"$PREFIX_CODE{}\""
+  else
+    eval "$data_cmd" | fzf --bind="enter:execute-silent($copy_notify_cmd)"
+  fi
 
 fi
-
 exit 0
