Updated

diff --git a/scripts/wfrecord b/scripts/wfrecord
--- a/scripts/wfrecord
+++ b/scripts/wfrecord
@@ -3,6 +3,15 @@
 
 # active=$(pamixer --list-sources | grep -v "Suspended" | head -n1 | awk '{print $2}' | tr -d '"')
 
+checkIfFailed() {
+  sleep 1
+  if ! kill -0 "$1" 2>/dev/null; then
+    pkill -RTMIN+8 waybar
+    echo "wf-recorder failed"
+    exit 1
+  fi
+}
+
 videoDir=~/Videos
 active=$(pactl get-default-sink).monitor
 mkdir -p $videoDir
@@ -15,7 +24,8 @@ echo $filename
 if [ -z $(pgrep wf-recorder) ]; then
   if [ "$1" == "-s" ]; then
     # wf-recorder -f $videoDir/$filename -a -g "$(slurp)" >/dev/null 2>&1 &
-    wf-recorder -f $videoDir/$filename -a="$active" -g "$(slurp)" >/dev/null 2>&1 &
+    wf-recorder -f $videoDir/$filename -a="$active" -g "$(slurp)" >/dev/null &
+    checkIfFailed $! &
     while [ -n "$(pgrep -x slurp)" ]; do
       sleep 0.5
     done
@@ -23,7 +33,8 @@ if [ -z $(pgrep wf-recorder) ]; then
     pkill -RTMIN+8 waybar
   else
     # wf-recorder -f $videoDir/$filename -a >/dev/null 2>&1 &
-    wf-recorder -f $videoDir/$filename -a="$active" >/dev/null 2>&1 &
+    wf-recorder -f $videoDir/$filename -a="$active" >/dev/null &
+    checkIfFailed $! &
     pkill -RTMIN+8 waybar
   fi
 else
